services:
  sql:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Password@1"
    platform: "linux/amd64"
    ports:
      - "1434:1433"